[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Disable secrets scanning for Vite environment variables
  # These are public client-side variables, not secrets
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "VITE_*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200